### ISSUE TITLE
Error with getAnnotation

### ISSUE THREAD

**Issue by libell1** [swaruplabUCI/ArchRtoSignac#26]
Hello,

Thanks for making this code! I am trying to use it, but am running into this error for the annotations:
> annotations <- getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38") # UCSC style
[1] "In Progress:"
[1] "Extract genomic ranges from EnsDb object and prepare annotation"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 06s
 Error in .order_seqlevels(chrom_sizes[, "chrom"]) : 
  !anyNA(m32) is not TRUE 

Any help solving this error would be great, thanks!

**Comment by rootze** [comment]
@libell1 Thanks for using the ArchRtoSignac package. Please let me know the version of your Signac and Seurat packages. 
The error you reported may be due to package version of `GenomeInfoDb` (https://github.com/Bioconductor/GenomeInfoDb/issues/32).  It may also be due to other unforeseen circumstances. The new version of Seurat V5 may also have compatible issues with different packages for a while before everything catches up.

**Comment by libell1** [comment]
Hi! I have Seurat 4.3.0.1 and Signac 1.10.0 Thanks!
> packageVersion("Seurat")
[1] '4.3.0.1'
> packageVersion("Signac")
[1] '1.10.0'

**Comment by rootze** [comment]
@libell1 I hope you have solved the problem. Please let me know if it is due to the package `GenomeInfoDb` as mentioned above. For now I will close this issue, but feel free to reopen it if needed
